name = "spotify_link_extension_worker"
type = "javascript"
workers_dev = true
compatibility_date = "2021-12-03"
kv_namespaces = [
  { binding = "SESSION_KV", preview_id = "01ecaebc449e406ca7c5fb1e45b6dc63", id = "e4c4f74e619748bea00638eba90341e8" }
]
[vars]
WORKERS_RS_VERSION = "0.0.7"
SESSION_TTL = 2592000 # 30 days

[build]
command = "cargo install -q worker-build && worker-build --release" # required

[build.upload]
dir    = "build/worker"
format = "modules"
main   = "./shim.mjs"

[[build.upload.rules]]
globs = ["**/*.wasm"]
type  = "CompiledWasm"

# read more about configuring your Worker via wrangler.toml at:
# https://developers.cloudflare.com/workers/cli-wrangler/configuration